
GET http://localhost:1337/cams?slug=st-regis-princeville-cam

###
GET http://localhost:1337/cams?id=2


###
GET http://localhost:1337/cams


### Search on term
GET http://localhost:1337/cams?title_contains=regis


